# Generated by Django 4.2.7 on 2023-12-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_source_alter_contactus_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.SmallIntegerField(choices=[(2, 'Dollar'), (1, 'Euro')], default=2),
        ),
    ]
